import os from "node:os";
import path from "node:path";

import { describe, expect, it, vi } from "vitest";

import {
  buildDependencyManifest,
  buildDependencyOutputDir,
  buildDiscoverJarCommand,
  buildDiscoverTopLevelArchiveCommand,
  discoverJarCandidates,
  formatDependenciesText,
  jarPathFromJavaArgs,
  parseJarCandidateLines,
  parsePomProperties,
  runReadOnlyExecWithRetry,
  sortJarCandidates,
  type DependencyJarInfo
} from "../src/dependencies.js";

describe("dependencies", () => {
  it("parses Java -jar arguments", () => {
    expect(jarPathFromJavaArgs(["java", "-Dspring.profiles.active=prod", "-jar", "/app/server.jar"])).toBe(
      "/app/server.jar"
    );
    expect(jarPathFromJavaArgs(["java", "-jar", "server.jar"], "/app")).toBe("/app/server.jar");
    expect(jarPathFromJavaArgs(["java", "org.example.Main"])).toBeUndefined();
  });

  it("parses and sorts Java archive candidates", () => {
    const candidates = parseJarCandidateLines(
      [
        "scan\t/opt/app/helper.jar",
        "scan\t/opt/saas/tax-workflow-server.war",
        "scan\t/opt/saas/agent/skywalking-agent.jar",
        "process\t/app/server.jar",
        "scan\t/opt/app/helper.jar",
        "scan\t/opt/app/readme.txt"
      ].join("\n")
    );

    expect(candidates).toEqual([
      { source: "process", path: "/app/server.jar" },
      { source: "scan", path: "/opt/saas/tax-workflow-server.war" },
      { source: "scan", path: "/opt/app/helper.jar" },
      { source: "scan", path: "/opt/saas/agent/skywalking-agent.jar" }
    ]);
    expect(sortJarCandidates([{ source: "provided", path: "/x/a.jar" }, { source: "process", path: "/x/b.jar" }])[0]?.source).toBe(
      "provided"
    );
  });

  it("builds remote discovery shell command", () => {
    const command = buildDiscoverJarCommand(["/app"]);

    expect(command).toContain("/proc/[0-9]*/cmdline");
    expect(command).toContain("awk 'prev == \"-jar\"");
    expect(command).toContain("find '/app' -maxdepth 5 -type f \\( -name '*.jar' -o -name '*.war' \\)");
    expect(command).toContain("|| true");
    expect(command.endsWith("exit 0")).toBe(true);
  });

  it("builds top-level archive discovery shell command", () => {
    const command = buildDiscoverTopLevelArchiveCommand(["/opt/saas"]);

    expect(command).toContain("find '/opt/saas' -maxdepth 1 -type f \\( -name '*.jar' -o -name '*.war' \\)");
    expect(command).not.toContain("/proc/[0-9]*/cmdline");
    expect(command.endsWith("exit 0")).toBe(true);
  });

  it("uses top-level archive discovery before full recursive discovery", async () => {
    const execCommand = vi.fn().mockResolvedValue({
      stdout: "scan\t/opt/saas/tax-invoice-business-server.war\n",
      stderr: "",
      error: ""
    });

    const candidates = await discoverJarCandidates(
      { execCommand } as never,
      {
        namespace: "tax-digital",
        pod: "tax-invoice-business-server-xxx",
        container: "container-tax-invoice-business-server"
      }
    );

    expect(candidates).toEqual([{ source: "scan", path: "/opt/saas/tax-invoice-business-server.war" }]);
    expect(execCommand).toHaveBeenCalledTimes(1);
    expect(execCommand.mock.calls[0]?.[0].command[2]).toContain("-maxdepth 1");
  });

  it("retries transient read-only exec socket resets", async () => {
    let attempts = 0;
    const result = await runReadOnlyExecWithRetry(
      async () => {
        attempts += 1;
        if (attempts < 3) {
          throw new Error("socket hang up");
        }
        return "ok";
      },
      { attempts: 3, delayMs: 0 }
    );

    expect(result).toBe("ok");
    expect(attempts).toBe(3);
  });

  it("does not retry non-transient read-only exec errors", async () => {
    let attempts = 0;

    await expect(
      runReadOnlyExecWithRetry(
        async () => {
          attempts += 1;
          throw new Error("permission denied");
        },
        { attempts: 3, delayMs: 0 }
      )
    ).rejects.toThrow("permission denied");
    expect(attempts).toBe(1);
  });

  it("builds dependency output directories", () => {
    expect(
      buildDependencyOutputDir("/home/me", { namespace: "tax-digital", workload: "tax invoice/server" }, new Date(2026, 6, 1, 9, 8, 7))
    ).toBe(path.join("/home/me", "Downloads", "bosscli", "dependencies", "tax-digital", "tax_invoice_server", "20260701_090807"));
  });

  it("parses pom.properties Maven coordinates", () => {
    expect(
      parsePomProperties(
        [
          "#Generated by Maven",
          "groupId=org.springframework.boot",
          "artifactId=spring-boot",
          "version=2.7.18"
        ].join("\n")
      )
    ).toEqual({
      groupId: "org.springframework.boot",
      artifactId: "spring-boot",
      version: "2.7.18"
    });
  });

  it("formats dependency manifests for human-readable output", () => {
    const dependency: DependencyJarInfo = {
      fileName: "spring-boot.jar",
      path: path.join(os.tmpdir(), "spring-boot.jar"),
      size: 2048,
      sha256: "abc",
      groupId: "org.springframework.boot",
      artifactId: "spring-boot",
      version: "2.7.18"
    };
    const manifest = buildDependencyManifest({
      target: {
        namespace: "tax-digital",
        workload: "tax-api-proxy-server",
        pod: "tax-api-proxy-server-xxx",
        container: "container-tax-api-proxy-server"
      },
      remoteJarPath: "/app/server.jar",
      appJarPath: path.join(os.tmpdir(), "server.jar"),
      appJarFileName: "server.jar",
      appStats: { size: 4096, sha256: "def" },
      dependencies: [dependency]
    });

    expect(manifest.remoteJarPath).toBe("/app/server.jar");
    expect(manifest.dependencies).toHaveLength(1);
    expect(formatDependenciesText(manifest)).toContain("org.springframework.boot:spring-boot:2.7.18");
  });
});
