import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import {
  buildDependencyManifest,
  buildDependencyOutputDir,
  buildDiscoverJarCommand,
  formatDependenciesText,
  jarPathFromJavaArgs,
  parseJarCandidateLines,
  parsePomProperties,
  sortJarCandidates,
  type DependencyJarInfo
} from "../src/dependencies.js";

describe("dependencies", () => {
  it("parses Java -jar arguments", () => {
    expect(jarPathFromJavaArgs(["java", "-Dspring.profiles.active=prod", "-jar", "/app/server.jar"])).toBe(
      "/app/server.jar"
    );
    expect(jarPathFromJavaArgs(["java", "-jar", "server.jar"], "/app")).toBe("/app/server.jar");
    expect(jarPathFromJavaArgs(["java", "org.example.Main"])).toBeUndefined();
  });

  it("parses and sorts jar candidates", () => {
    const candidates = parseJarCandidateLines(
      [
        "scan\t/opt/app/helper.jar",
        "process\t/app/server.jar",
        "scan\t/opt/app/helper.jar",
        "scan\t/opt/app/readme.txt"
      ].join("\n")
    );

    expect(candidates).toEqual([
      { source: "process", path: "/app/server.jar" },
      { source: "scan", path: "/opt/app/helper.jar" }
    ]);
    expect(sortJarCandidates([{ source: "provided", path: "/x/a.jar" }, { source: "process", path: "/x/b.jar" }])[0]?.source).toBe(
      "provided"
    );
  });

  it("builds remote discovery shell command", () => {
    const command = buildDiscoverJarCommand(["/app"]);

    expect(command).toContain("/proc/[0-9]*/cmdline");
    expect(command).toContain("awk 'prev == \"-jar\"");
    expect(command).toContain("find '/app' -maxdepth 5 -type f -name '*.jar'");
  });

  it("builds dependency output directories", () => {
    expect(
      buildDependencyOutputDir("/home/me", { namespace: "tax-digital", workload: "tax invoice/server" }, new Date(2026, 6, 1, 9, 8, 7))
    ).toBe(path.join("/home/me", "Downloads", "bosscli", "dependencies", "tax-digital", "tax_invoice_server", "20260701_090807"));
  });

  it("parses pom.properties Maven coordinates", () => {
    expect(
      parsePomProperties(
        [
          "#Generated by Maven",
          "groupId=org.springframework.boot",
          "artifactId=spring-boot",
          "version=2.7.18"
        ].join("\n")
      )
    ).toEqual({
      groupId: "org.springframework.boot",
      artifactId: "spring-boot",
      version: "2.7.18"
    });
  });

  it("formats dependency manifests for human-readable output", () => {
    const dependency: DependencyJarInfo = {
      fileName: "spring-boot.jar",
      path: path.join(os.tmpdir(), "spring-boot.jar"),
      size: 2048,
      sha256: "abc",
      groupId: "org.springframework.boot",
      artifactId: "spring-boot",
      version: "2.7.18"
    };
    const manifest = buildDependencyManifest({
      target: {
        namespace: "tax-digital",
        workload: "tax-api-proxy-server",
        pod: "tax-api-proxy-server-xxx",
        container: "container-tax-api-proxy-server"
      },
      remoteJarPath: "/app/server.jar",
      appJarPath: path.join(os.tmpdir(), "server.jar"),
      appJarFileName: "server.jar",
      appStats: { size: 4096, sha256: "def" },
      dependencies: [dependency]
    });

    expect(manifest.remoteJarPath).toBe("/app/server.jar");
    expect(manifest.dependencies).toHaveLength(1);
    expect(formatDependenciesText(manifest)).toContain("org.springframework.boot:spring-boot:2.7.18");
  });
});
