import type { LexiangInterfaceInfo } from "./types.js";

// Generated by scripts/generate-lexiang-medical-snapshot.py.
// Source Word document is intentionally not bundled with the package.
export const LEXIANG_MEDICAL_INTERFACES = [
  {
    "category": "登陆认证",
    "name": "请求登录电子税务局",
    "path": "/api/standard/v1/rpa/100101001",
    "method": "POST",
    "description": "用于RPA模式下登陆电子税务局。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.1.1 请求登录电子税务局",
    "fields": [
      {
        "key": "nsrsbh",
        "name": "纳税人识别号/统一社会信用代码",
        "type": "String",
        "length": "26",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "kpdbm",
        "name": "开票点编码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "开票点编码",
        "group": "请求参数"
      }
    ],
    "template": {
      "nsrsbh": "",
      "kpdbm": ""
    }
  },
  {
    "category": "登陆认证",
    "name": "确认登录电子税务局",
    "path": "/api/standard/v1/rpa/100101002",
    "method": "POST",
    "description": "单位内部系统根据纳税人识别号、办税员账号、手机验证码信息向税务数字服务平台发起确认登录请求，登录电子税务局。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.1.2 确认登录电子税务局",
    "fields": [
      {
        "key": "nsrsbh",
        "name": "纳税人识别号/统一社会信用代码",
        "type": "String",
        "length": "26",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "kpdbm",
        "name": "开票点编码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "dxyzm",
        "name": "短信验证码",
        "type": "String",
        "length": "6",
        "required": "是",
        "description": "",
        "group": "请求参数"
      }
    ],
    "template": {
      "nsrsbh": "",
      "kpdbm": "",
      "dxyzm": ""
    }
  },
  {
    "category": "登陆认证",
    "name": "请求电子税务局二维码认证",
    "path": "/api/standard/v1/rpa/100101004",
    "method": "POST",
    "description": "单位内部系统根据纳税人识别号、办税员账号向税务数字服务平台发起电子税务局二维码认证请求。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.1.3 请求电子税务局二维码认证",
    "fields": [
      {
        "key": "nsrsbh",
        "name": "纳税人识别号/统一社会信用代码",
        "type": "String",
        "length": "26",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "kpdbm",
        "name": "开票点编码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "请求参数"
      }
    ],
    "template": {
      "nsrsbh": "",
      "kpdbm": ""
    }
  },
  {
    "category": "登陆认证",
    "name": "查询电子税务局登陆及身份授权状态",
    "path": "/api/standard/v1/rpa/100101003",
    "method": "POST",
    "description": "企业根据纳税人识别号、办税员账号向税务数字服务平台查询电子税务局登陆和身份授权状态。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.1.4 查询电子税务局登陆及身份授权状态",
    "fields": [
      {
        "key": "nsrsbh",
        "name": "纳税人识别号/统一社会信用代码",
        "type": "String",
        "length": "26",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "kpdbm",
        "name": "开票点编码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "请求参数"
      }
    ],
    "template": {
      "nsrsbh": "",
      "kpdbm": ""
    }
  },
  {
    "category": "",
    "name": "医疗门诊全电蓝字发票开具",
    "path": "/api/medical/v1/rpa/10210100111",
    "method": "POST",
    "description": "单位内部系统发起开具蓝票服务请求，实时开具全电蓝字发票。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.2.1 医疗门诊全电蓝字发票开具",
    "fields": [
      {
        "key": "serialNumber",
        "name": "流水号",
        "type": "String",
        "length": "32",
        "required": "是",
        "description": "用于唯一标识一笔业务，针对同一笔业务若变更流水号则会导致重复开票",
        "group": "请求参数"
      },
      {
        "key": "kpdbm",
        "name": "开票点编码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "kpms",
        "name": "开票模式",
        "type": "String",
        "length": "1",
        "required": "否",
        "description": "0：直接开具；1、审核开票（仅推送待开信息，在乐享平台审核开具）；2、患者自助开票（仅推送订单信息，患者扫码后自助申请开票；订单信息最多保留3个月，超期需到窗口人工开票）。如未传入，默认直接开具。",
        "group": "请求参数"
      },
      {
        "key": "data",
        "name": "发票数据",
        "type": "String",
        "length": "",
        "required": "是",
        "description": "发票数据，详见A-1发票数据data",
        "group": "请求参数"
      },
      {
        "key": "fppz",
        "name": "发票票种",
        "type": "String",
        "length": "2",
        "required": "是",
        "description": "发票票种。01：全电专；02：全电普。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "qyDm",
        "name": "区域代码",
        "type": "String",
        "length": "2",
        "required": "否",
        "description": "省级行政区域代码详见附录2",
        "group": "A-1 发票数据data"
      },
      {
        "key": "cezslxDm",
        "name": "差额征税类型代码",
        "type": "String",
        "length": "2",
        "required": "否",
        "description": "空：非差额发票 01：全额开票 02：差额开票",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfnsrsbh",
        "name": "（销售方）统一社会信用代码/纳税人识别号/身份证件号码",
        "type": "String",
        "length": "26",
        "required": "是",
        "description": "（销售方）统一社会信用代码/纳税人识别号/身份证件号码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfmc",
        "name": "(销售方)名称",
        "type": "String",
        "length": "300",
        "required": "是",
        "description": "(销售方)名称",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfdz",
        "name": "销售方地址",
        "type": "String",
        "length": "300",
        "required": "否",
        "description": "销售方地址",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfdh",
        "name": "销售方电话",
        "type": "String",
        "length": "60",
        "required": "否",
        "description": "销售方电话",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfkhh",
        "name": "销售方开户行",
        "type": "String",
        "length": "120",
        "required": "否",
        "description": "销售方开户行",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfzh",
        "name": "销售方账号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "销售方账号",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfnsrsbh",
        "name": "（购买方）统一社会信用代码/纳税人识别号/身份证件号码",
        "type": "String",
        "length": "20",
        "required": "否",
        "description": "（购买方）统一社会信用代码/纳税人识别号/身份证件号码。开具数电专票时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfmc",
        "name": "(购买方)名称",
        "type": "String",
        "length": "300",
        "required": "是",
        "description": "(购买方)名称",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfdz",
        "name": "购买方地址",
        "type": "String",
        "length": "300",
        "required": "否",
        "description": "购买方地址",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfdh",
        "name": "购买方电话",
        "type": "String",
        "length": "60",
        "required": "否",
        "description": "购买方电话",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfkhh",
        "name": "购买方开户行",
        "type": "String",
        "length": "120",
        "required": "否",
        "description": "购买方开户行",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfzh",
        "name": "购买方账号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "购买方账号",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfjbr",
        "name": "购买方经办人姓名",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "购买方经办人姓名",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jbrsfzjhm",
        "name": "购买方经办人证件号码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "购买方经办人证件号码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfjbrlxdh",
        "name": "购买方经办人联系电话",
        "type": "String",
        "length": "60",
        "required": "否",
        "description": "购买方经办人联系电话",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfzrrbz",
        "name": "购买方自然人标志",
        "type": "String",
        "length": "1",
        "required": "否",
        "description": "Y：购买方是自然人，N：购买方非自 然人。未传入则默认为非自然人。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hjje",
        "name": "合计金额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "合计金额",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hjse",
        "name": "合计税额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "合计税额",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jshj",
        "name": "价税合计",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "价税合计",
        "group": "A-1 发票数据data"
      },
      {
        "key": "skyhmc",
        "name": "收款银行名称",
        "type": "String",
        "length": "120",
        "required": "否",
        "description": "收款银行名称",
        "group": "A-1 发票数据data"
      },
      {
        "key": "skyhzh",
        "name": "收款银行账号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "收款银行账号",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jsfs",
        "name": "结算方式",
        "type": "String",
        "length": "1",
        "required": "否",
        "description": "结算方式详见附录3",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ysxwfsd",
        "name": "应税行为发生地",
        "type": "String",
        "length": "11",
        "required": "否",
        "description": "应税行为发生地",
        "group": "A-1 发票数据data"
      },
      {
        "key": "kpr",
        "name": "开票人",
        "type": "String",
        "length": "50",
        "required": "是",
        "description": "开票人",
        "group": "A-1 发票数据data"
      },
      {
        "key": "kprzjhm",
        "name": "开票人证件号码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "开票人证件号码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "kprzjlx",
        "name": "开票人证件类型",
        "type": "String",
        "length": "4",
        "required": "否",
        "description": "证件类型编码，见附录11：开票人证件类型",
        "group": "A-1 发票数据data"
      },
      {
        "key": "skrxm",
        "name": "收款人姓名",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "fhrxm",
        "name": "复核人姓名",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "bz",
        "name": "备注",
        "type": "String",
        "length": "300",
        "required": "否",
        "description": "备注",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zfbzh",
        "name": "交款人支付宝账户",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "交款人如果使用支付宝结算，可传入交款人的支付宝UserID，用于电子票据归集到支付宝发票管家",
        "group": "A-1 发票数据data"
      },
      {
        "key": "wxddh",
        "name": "微信支付订单号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "微信结算时，可传入交款人支付成功的订单号，用来发微信服务通知",
        "group": "A-1 发票数据data"
      },
      {
        "key": "sjhm",
        "name": "发票接收手机号",
        "type": "String",
        "length": "11",
        "required": "否",
        "description": "如需要用于电子票归集、电子票据短信通知，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yxdz",
        "name": "发票接收邮箱",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "如需用于电子票归集、电子票据邮箱通知，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "klx",
        "name": "卡类型",
        "type": "String",
        "length": "10",
        "required": "否",
        "description": "附录1：卡类型列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "kh",
        "name": "卡号",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "根据卡类型填写",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yljglx",
        "name": "医疗机构类型",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "填写医疗机构类型名称。值域见附录8:医疗机构类型",
        "group": "A-1 发票数据data"
      },
      {
        "key": "qtyljglx",
        "name": "其他医疗机构类型",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "填写上述医疗机构类型没有的类型，“医疗机构类型”和“其他医疗机构类型”只能填写一个",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ybjgbm",
        "name": "医保机构编码",
        "type": "String",
        "length": "60",
        "required": "否",
        "description": "医保机构的唯一编码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yblxbm",
        "name": "医保类型编码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "01：职工基本医疗保险02：城乡居民基本医疗保险03：离休04：其他医疗保险05：自费",
        "group": "A-1 发票数据data"
      },
      {
        "key": "qtyblx",
        "name": "其他医保类型",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "填写上述医保类型代码没有的类型，“医保类型代码”和“其他医保类型”只能填写一个",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzybbh",
        "name": "患者医保编号",
        "type": "String",
        "length": "20",
        "required": "否",
        "description": "参保人在医保系统中的唯一标识(医保号)，医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ybxzqhm",
        "name": "参保地医保区划",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "医保机构的唯一标识，医保结算时必须填写",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jzrq",
        "name": "就诊日期",
        "type": "String",
        "length": "19",
        "required": "是",
        "description": "患者就医时间格式：yyyy-MM-dd HH:mm:ss",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jzksmc",
        "name": "就诊科室名称",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzjzbh",
        "name": "患者就诊编号",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "患者每次就诊一次就生成的一个新的编号。（患者登记号）",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzwyid",
        "name": "患者唯一ID",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "患者在业务系统中的唯一标识ID，类似身份证号码。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzxm",
        "name": "患者姓名",
        "type": "String",
        "length": "50",
        "required": "是",
        "description": "患者姓名。未填入，默认取购买方名称",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzsfzjlxDm",
        "name": "患者身份证件类型代码",
        "type": "String",
        "length": "3",
        "required": "是",
        "description": "患者身份证件类型代码，详见附录7。未填入默认为201：居民身份证",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzsfzjhm",
        "name": "患者身份证件号码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "未填入且购买方是自然人时，默认取购买方身份证件号码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xb",
        "name": "性别",
        "type": "String",
        "length": "4",
        "required": "是",
        "description": "值为：男、女",
        "group": "A-1 发票数据data"
      },
      {
        "key": "nl",
        "name": "年龄",
        "type": "String",
        "length": "10",
        "required": "是",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "blh",
        "name": "病历号",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jbbm",
        "name": "疾病编码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "tsbzmc",
        "name": "特殊病种名称",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "对接医保上传电子结算凭证，附加信息：",
        "name": "",
        "type": "",
        "length": "",
        "required": "",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyzddm",
        "name": "主要诊断代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyzdmc",
        "name": "主要诊断名称",
        "type": "String",
        "length": "255",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "cyzddm",
        "name": "次要诊断代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "cyzdmc",
        "name": "次要诊断名称",
        "type": "String",
        "length": "255",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jydybqh",
        "name": "就医地医保区划",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "就医地医保机构的唯一标识，医保结算时必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xzlx",
        "name": "险种类型",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "详见附录9，医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jzkssj",
        "name": "开始时间",
        "type": "String",
        "length": "19",
        "required": "否",
        "description": "格式：yyyy-MM-dd HH:mm:ss对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jzjssj",
        "name": "结束时间",
        "type": "String",
        "length": "19",
        "required": "否",
        "description": "格式：yyyy-MM-dd HH:mm:ss 对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "sylb",
        "name": "生育类别",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jhsysslb",
        "name": "计划生育手术类别",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "tc",
        "name": "胎次",
        "type": "Number",
        "length": "3",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yzs",
        "name": "孕周数",
        "type": "Number",
        "length": "2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "tes",
        "name": "胎儿数",
        "type": "Number",
        "length": "3",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "lyfs",
        "name": "离院方式",
        "type": "String",
        "length": "3",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ssczdm",
        "name": "手术操作代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ssczmc",
        "name": "手术操作名称",
        "type": "String",
        "length": "500",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "swrq",
        "name": "死亡日期",
        "type": "String",
        "length": "8",
        "required": "否",
        "description": "yyyyMMdd",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zzysdm",
        "name": "主诊医师代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zzysxm",
        "name": "主诊医师姓名",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ylfl",
        "name": "医疗分类",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "详见附录10。对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ddyljgbh",
        "name": "定点医疗机构编号",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ddyljgmc",
        "name": "定点医疗机构名称",
        "type": "String",
        "length": "255",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jgjgdm",
        "name": "监管机构代码",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grzhzf",
        "name": "个人账户支付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "按政策规定用个人账户支付参保人的医疗费用（含基本医疗保险目录范围内和目录范围外的费用）；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "fhfwje",
        "name": "符合范围金额",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "如无金额，填写0。医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ybtcjjzf",
        "name": "医保统筹基金支付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "患者本次就医所发生的医疗费用中按规定由基本医疗保险统筹基金支付的金额；如无金额，填写0。医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "qtybzf",
        "name": "其它医保支付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "患者本次就医所发生的医疗费用中按规定由大病保险、医疗救助、公务员医疗补助、大额补充、企业补充等基金或资金支付的金额；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zfje",
        "name": "自费金额",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "患者本次就医所发生的医疗费用中按照有关规定不属于基本医疗保险目录范围而全部由个人支付的费用；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grzf1",
        "name": "个人自负",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "医保患者起付标准内个人支付费用；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grzf2",
        "name": "个人自付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "患者本次就医所发生的医疗费用中由个人负担的属于基本医疗保险目录范围内自付部分的金额；开展按病种、病组、床日等打包付费方式且由患者定额付费的费用。该项为个人所得税大病医疗专项附加扣除信；息项如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grxjzf",
        "name": "个人现金支付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "个人通过现金、银行卡、微信、支付宝等渠道支付的金额；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yjje",
        "name": "预缴金额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "bjje",
        "name": "补缴金额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "tfje",
        "name": "退费金额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grzhye",
        "name": "个人账户余额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "bxzje",
        "name": "报销总金额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "医保结算后返回的总金额",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jsh",
        "name": "结算号",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "医保结算后生成的号码/入账唯一值，医保实时结算必填。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jssj",
        "name": "结算时间",
        "type": "String",
        "length": "19",
        "required": "否",
        "description": "患者就医时间，格式：yyyy-MM-dd HH:mm:ss，医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ywrq",
        "name": "业务日期",
        "type": "date",
        "length": "",
        "required": "否",
        "description": "业务日期，格式yyyy-MM-dd HH:mm:ss",
        "group": "A-1 发票数据data"
      },
      {
        "key": "fpmx",
        "name": "发票明细",
        "type": "List",
        "length": "",
        "required": "是",
        "description": "发票明细详见A-2,JSON格式列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "sszdyysmx",
        "name": "省市自定义要素明细",
        "type": "List",
        "length": "",
        "required": "否",
        "description": "省市自定义要素明细详见A-4,JSON格式列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zdxxlb",
        "name": "诊断信息列表",
        "type": "List",
        "length": "",
        "required": "否",
        "description": "诊断信息列表详见A-5,JSON格式列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "mxxh",
        "name": "明细序号",
        "type": "Number",
        "length": "8",
        "required": "是",
        "description": "明细序号",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "xmmc",
        "name": "项目名称",
        "type": "String",
        "length": "200",
        "required": "是",
        "description": "项目名称，无需传入简称",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "ggxh",
        "name": "规格型号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "规格型号",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "dw",
        "name": "单位",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "单位",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "sl",
        "name": "数量",
        "type": "String",
        "length": "15,13",
        "required": "否",
        "description": "数量如“单位”栏次非空，则本栏次必须非空。对接医保上传电子结算凭证时，必填",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "dj",
        "name": "单价",
        "type": "String",
        "length": "15,13",
        "required": "否",
        "description": "单价如“单位”栏次非空，则本栏次必须非空。对接医保上传电子结算凭证时，必填",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "je",
        "name": "金额（不含税）",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "金额（不含税）",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "slv",
        "name": "增值税税率/征收率",
        "type": "Number",
        "length": "10,6",
        "required": "是",
        "description": "增值税税率/征收率",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "se",
        "name": "税额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "税额",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "hsje",
        "name": "含税金额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "含税金额",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "kce",
        "name": "扣除额",
        "type": "Number",
        "length": "16,2",
        "required": "否",
        "description": "扣除额",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "spfwssflbm",
        "name": "商品和服务税收分类编码",
        "type": "String",
        "length": "19",
        "required": "是",
        "description": "商品和服务税收分类编码",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "fphxz",
        "name": "发票行性质",
        "type": "String",
        "length": "2",
        "required": "是",
        "description": "发票行性质00:正常行01:折扣行02:被折扣行",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "yhzcbs",
        "name": "优惠政策标识",
        "type": "String",
        "length": "2",
        "required": "否",
        "description": "优惠政策标识详见附录4",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "fymx",
        "name": "费用明细",
        "type": "String",
        "length": "200",
        "required": "否",
        "description": "最大33个汉字乐企开票时可用，RPA暂不支持",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "ylfwgbm",
        "name": "医疗服务贯标码",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "乐企开票时可用，RPA暂不支持",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "qt",
        "name": "其他",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "其他",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "sszdyysxh",
        "name": "省市自定义要素序号",
        "type": "Number",
        "length": "2",
        "required": "是",
        "description": "省市自定义要素序号从“1”开始的连续正整数",
        "group": "A-4 省市自定义要素明细sszdyysList"
      },
      {
        "key": "sszdyysmc",
        "name": "省市自定义要素名称",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "若“省市自定义要素内容”栏次非空，则本栏次必须非空；",
        "group": "A-4 省市自定义要素明细sszdyysList"
      },
      {
        "key": "sszdyysnr",
        "name": "省市自定义要素内容",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "若“省市自定义要素名称”栏次非空，则本栏次必须非空",
        "group": "A-4 省市自定义要素明细sszdyysList"
      },
      {
        "key": "mxxh",
        "name": "明细序号",
        "type": "Number",
        "length": "8",
        "required": "是",
        "description": "",
        "group": "A-4 诊断列表zdxxlb"
      },
      {
        "key": "cryzdlb",
        "name": "出入院诊断类别",
        "type": "String",
        "length": "6",
        "required": "是",
        "description": "",
        "group": "A-4 诊断列表zdxxlb"
      },
      {
        "key": "zdlb",
        "name": "诊断类别",
        "type": "String",
        "length": "3",
        "required": "是",
        "description": "",
        "group": "A-4 诊断列表zdxxlb"
      },
      {
        "key": "zzzbz",
        "name": "主诊断标志",
        "type": "String",
        "length": "3",
        "required": "是",
        "description": "",
        "group": "A-4 诊断列表zdxxlb"
      },
      {
        "key": "zddm",
        "name": "诊断代码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "A-4 诊断列表zdxxlb"
      },
      {
        "key": "zdmc",
        "name": "诊断名称",
        "type": "String",
        "length": "255",
        "required": "是",
        "description": "",
        "group": "A-4 诊断列表zdxxlb"
      },
      {
        "key": "zdsj",
        "name": "诊断时间",
        "type": "String",
        "length": "19",
        "required": "是",
        "description": "yyyy-MM-dd HH:mm:ss",
        "group": "A-4 诊断列表zdxxlb"
      },
      {
        "key": "zdysdm",
        "name": "诊断医师代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-4 诊断列表zdxxlb"
      },
      {
        "key": "zdysxm",
        "name": "诊断医师姓名",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-4 诊断列表zdxxlb"
      }
    ],
    "template": {
      "serialNumber": "",
      "kpdbm": "",
      "kpms": "",
      "data": {
        "fppz": "",
        "qyDm": "",
        "cezslxDm": "",
        "xsfnsrsbh": "",
        "xsfmc": "",
        "xsfdz": "",
        "xsfdh": "",
        "xsfkhh": "",
        "xsfzh": "",
        "gmfnsrsbh": "",
        "gmfmc": "",
        "gmfdz": "",
        "gmfdh": "",
        "gmfkhh": "",
        "gmfzh": "",
        "gmfjbr": "",
        "jbrsfzjhm": "",
        "gmfjbrlxdh": "",
        "gmfzrrbz": "",
        "hjje": 0,
        "hjse": 0,
        "jshj": 0,
        "skyhmc": "",
        "skyhzh": "",
        "jsfs": "",
        "ysxwfsd": "",
        "kpr": "",
        "kprzjhm": "",
        "kprzjlx": "",
        "skrxm": "",
        "fhrxm": "",
        "bz": "",
        "zfbzh": "",
        "wxddh": "",
        "sjhm": "",
        "yxdz": "",
        "klx": "",
        "kh": "",
        "yljglx": "",
        "qtyljglx": "",
        "ybjgbm": "",
        "yblxbm": "",
        "qtyblx": "",
        "hzybbh": "",
        "ybxzqhm": "",
        "jzrq": "",
        "jzksmc": "",
        "hzjzbh": "",
        "hzwyid": "",
        "hzxm": "",
        "hzsfzjlxDm": "",
        "hzsfzjhm": "",
        "xb": "",
        "nl": "",
        "blh": "",
        "jbbm": "",
        "tsbzmc": "",
        "对接医保上传电子结算凭证，附加信息：": "",
        "zyzddm": "",
        "zyzdmc": "",
        "cyzddm": "",
        "cyzdmc": "",
        "jydybqh": "",
        "xzlx": "",
        "jzkssj": "",
        "jzjssj": "",
        "sylb": "",
        "jhsysslb": "",
        "tc": 0,
        "yzs": 0,
        "tes": 0,
        "lyfs": "",
        "ssczdm": "",
        "ssczmc": "",
        "swrq": "",
        "zzysdm": "",
        "zzysxm": "",
        "ylfl": "",
        "ddyljgbh": "",
        "ddyljgmc": "",
        "jgjgdm": "",
        "grzhzf": 0,
        "fhfwje": 0,
        "ybtcjjzf": 0,
        "qtybzf": 0,
        "zfje": 0,
        "grzf1": 0,
        "grzf2": 0,
        "grxjzf": 0,
        "yjje": 0,
        "bjje": 0,
        "tfje": 0,
        "grzhye": 0,
        "bxzje": 0,
        "jsh": "",
        "jssj": "",
        "ywrq": "",
        "fpmx": [
          {
            "mxxh": 0,
            "xmmc": "",
            "ggxh": "",
            "dw": "",
            "sl": "",
            "dj": "",
            "je": 0,
            "slv": 0,
            "se": 0,
            "hsje": 0,
            "kce": 0,
            "spfwssflbm": "",
            "fphxz": "",
            "yhzcbs": "",
            "fymx": "",
            "ylfwgbm": "",
            "qt": ""
          }
        ],
        "sszdyysmx": [
          {
            "sszdyysxh": 0,
            "sszdyysmc": "",
            "sszdyysnr": ""
          }
        ],
        "zdxxlb": [
          {
            "mxxh": 0,
            "cryzdlb": "",
            "zdlb": "",
            "zzzbz": "",
            "zddm": "",
            "zdmc": "",
            "zdsj": "",
            "zdysdm": "",
            "zdysxm": ""
          }
        ]
      }
    }
  },
  {
    "category": "",
    "name": "医疗住院全电蓝字发票开具",
    "path": "/api/medical/v1/rpa/10210100110",
    "method": "POST",
    "description": "单位内部系统发起开具蓝票服务请求，实时开具全电蓝字发票。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.2.2 医疗住院全电蓝字发票开具",
    "fields": [
      {
        "key": "serialNumber",
        "name": "流水号",
        "type": "String",
        "length": "32",
        "required": "是",
        "description": "用于唯一标识一笔业务，针对同一笔业务若变更流水号则会导致重复开票",
        "group": "请求参数"
      },
      {
        "key": "kpdbm",
        "name": "开票点编码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "kpms",
        "name": "开具模式",
        "type": "String",
        "length": "1",
        "required": "否",
        "description": "0：直接开具；1、审核开票（仅推送待开信息，在乐享平台审核开具）；2、患者自助开票（仅推送订单信息，患者扫码后自助申请开票；订单信息最多保留3个月，超期需到窗口人工开票）。如未传入，默认直接开具。",
        "group": "请求参数"
      },
      {
        "key": "data",
        "name": "发票数据",
        "type": "String",
        "length": "",
        "required": "是",
        "description": "发票数据，详见A-1发票数据data",
        "group": "请求参数"
      },
      {
        "key": "fppz",
        "name": "发票票种",
        "type": "String",
        "length": "2",
        "required": "是",
        "description": "发票票种。01：全电专；02：全电普。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "qyDm",
        "name": "区域代码",
        "type": "String",
        "length": "2",
        "required": "否",
        "description": "省级行政区域代码详见附录2",
        "group": "A-1 发票数据data"
      },
      {
        "key": "cezslxDm",
        "name": "差额征税类型代码",
        "type": "String",
        "length": "2",
        "required": "否",
        "description": "空：非差额发票 01：全额开票 02：差额开票",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfnsrsbh",
        "name": "（销售方）统一社会信用代码/纳税人识别号/身份证件号码",
        "type": "String",
        "length": "26",
        "required": "是",
        "description": "（销售方）统一社会信用代码/纳税人识别号/身份证件号码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfmc",
        "name": "(销售方)名称",
        "type": "String",
        "length": "300",
        "required": "是",
        "description": "(销售方)名称",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfdz",
        "name": "销售方地址",
        "type": "String",
        "length": "300",
        "required": "否",
        "description": "销售方地址",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfdh",
        "name": "销售方电话",
        "type": "String",
        "length": "60",
        "required": "否",
        "description": "销售方电话",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfkhh",
        "name": "销售方开户行",
        "type": "String",
        "length": "120",
        "required": "否",
        "description": "销售方开户行",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xsfzh",
        "name": "销售方账号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "销售方账号",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfnsrsbh",
        "name": "（购买方）统一社会信用代码/纳税人识别号/身份证件号码",
        "type": "String",
        "length": "26",
        "required": "否",
        "description": "（购买方）统一社会信用代码/纳税人识别号/身份证件号码。开具数电专票时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfmc",
        "name": "(购买方)名称",
        "type": "String",
        "length": "300",
        "required": "是",
        "description": "(购买方)名称",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfdz",
        "name": "购买方地址",
        "type": "String",
        "length": "300",
        "required": "否",
        "description": "购买方地址",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfdh",
        "name": "购买方电话",
        "type": "String",
        "length": "60",
        "required": "否",
        "description": "购买方电话",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfkhh",
        "name": "购买方开户行",
        "type": "String",
        "length": "120",
        "required": "否",
        "description": "购买方开户行",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfzh",
        "name": "购买方账号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "购买方账号",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfjbr",
        "name": "购买方经办人姓名",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "购买方经办人姓名",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jbrsfzjhm",
        "name": "购买方经办人证件号码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "购买方经办人证件号码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfjbrlxdh",
        "name": "购买方经办人联系电话",
        "type": "String",
        "length": "60",
        "required": "否",
        "description": "购买方经办人联系电话",
        "group": "A-1 发票数据data"
      },
      {
        "key": "gmfzrrbz",
        "name": "购买方自然人标志",
        "type": "String",
        "length": "1",
        "required": "否",
        "description": "Y：购买方是自然人，N：购买方非自 然人。未传入则默认为非自然人。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hjje",
        "name": "合计金额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "合计金额",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hjse",
        "name": "合计税额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "合计税额",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jshj",
        "name": "价税合计",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "价税合计",
        "group": "A-1 发票数据data"
      },
      {
        "key": "skyhmc",
        "name": "收款银行名称",
        "type": "String",
        "length": "120",
        "required": "否",
        "description": "收款银行名称",
        "group": "A-1 发票数据data"
      },
      {
        "key": "skyhzh",
        "name": "收款银行账号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "收款银行账号",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jsfs",
        "name": "结算方式",
        "type": "String",
        "length": "1",
        "required": "否",
        "description": "结算方式详见附录3",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ysxwfsd",
        "name": "应税行为发生地",
        "type": "String",
        "length": "11",
        "required": "否",
        "description": "应税行为发生地",
        "group": "A-1 发票数据data"
      },
      {
        "key": "kpr",
        "name": "开票人",
        "type": "String",
        "length": "50",
        "required": "是",
        "description": "开票人",
        "group": "A-1 发票数据data"
      },
      {
        "key": "kprzjhm",
        "name": "开票人证件号码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "开票人证件号码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "kprzjlx",
        "name": "开票人证件类型",
        "type": "String",
        "length": "4",
        "required": "否",
        "description": "证件类型编码，见附录11：开票人证件类型",
        "group": "A-1 发票数据data"
      },
      {
        "key": "skrxm",
        "name": "收款人姓名",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "fhrxm",
        "name": "复核人姓名",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "bz",
        "name": "备注",
        "type": "String",
        "length": "300",
        "required": "否",
        "description": "备注",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zfbzh",
        "name": "交款人支付宝账户",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "交款人如果使用支付宝结算，可传入交款人的支付宝UserID，用于电子票据归集到支付宝发票管家",
        "group": "A-1 发票数据data"
      },
      {
        "key": "wxddh",
        "name": "微信支付订单号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "微信结算时，可传入交款人支付成功的订单号，用来发微信服务通知",
        "group": "A-1 发票数据data"
      },
      {
        "key": "sjhm",
        "name": "发票接收手机号",
        "type": "String",
        "length": "11",
        "required": "否",
        "description": "如需要用于电子票归集、电子票据短信通知，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yxdz",
        "name": "发票接收邮箱",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "如需用于电子票归集、电子票据邮箱通知，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "klx",
        "name": "卡类型",
        "type": "String",
        "length": "10",
        "required": "否",
        "description": "附录1：卡类型列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "kh",
        "name": "卡号",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "根据卡类型填写",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yljglx",
        "name": "医疗机构类型",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "填写医疗机构类型名称。值域见附录8:医疗机构类型代码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "qtyljglx",
        "name": "其他医疗机构类型",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "填写上述医疗机构类型没有的类型，“医疗机构类型”和“其他医疗机构类型”只能填写一个。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ybjgbm",
        "name": "医保机构编码",
        "type": "String",
        "length": "60",
        "required": "否",
        "description": "医保机构的唯一编码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yblxbm",
        "name": "医保类型编码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "01：职工基本医疗保险02：城乡居民基本医疗保险03：离休04：其他医疗保险05：自费",
        "group": "A-1 发票数据data"
      },
      {
        "key": "qtyblx",
        "name": "其他医保类型",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "填写上述医保类型代码没有的类型，“医保类型代码”和“其他医保类型”只能填写一个。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzybbh",
        "name": "患者医保编号",
        "type": "String",
        "length": "20",
        "required": "否",
        "description": "参保人在医保系统中的唯一标识(医保号)，医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ybxzqhm",
        "name": "参保地医保区划",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "医保机构的唯一标识，医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ryksmc",
        "name": "入院科室名称",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "cyksmc",
        "name": "出院科室名称",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzjzbh",
        "name": "患者住院号",
        "type": "String",
        "length": "20",
        "required": "是",
        "description": "从入院到出院结束后，整个流程的唯一号",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyjzbh",
        "name": "住院就诊编号",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "住院期间，存在多次结算，结算后会重新生成一个住院就诊编号，如无就诊编号，可等于患者住院号",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzwyid",
        "name": "患者唯一ID",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "患者在业务系统中的唯一标识ID，类似身份证号码。",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzxm",
        "name": "患者姓名",
        "type": "String",
        "length": "50",
        "required": "是",
        "description": "患者姓名。未填入，默认取购买方名称",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzsfzjlxDm",
        "name": "患者身份证件类型代码",
        "type": "String",
        "length": "3",
        "required": "是",
        "description": "患者身份证件类型代码，详见附录7。未填入默认为201：居民身份证",
        "group": "A-1 发票数据data"
      },
      {
        "key": "hzsfzjhm",
        "name": "患者身份证件号码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "未填入且购买方是自然人时，默认取购买方身份证件号码",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xb",
        "name": "性别",
        "type": "String",
        "length": "4",
        "required": "是",
        "description": "值为：男、女",
        "group": "A-1 发票数据data"
      },
      {
        "key": "nl",
        "name": "年龄",
        "type": "String",
        "length": "10",
        "required": "是",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "bq",
        "name": "病区",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ch",
        "name": "床号",
        "type": "String",
        "length": "20",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "blh",
        "name": "病历号",
        "type": "String",
        "length": "20",
        "required": "是",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jbbm",
        "name": "疾病编码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyrq",
        "name": "住院日期",
        "type": "String",
        "length": "10",
        "required": "是",
        "description": "格式:yyyy-MM-dd",
        "group": "A-1 发票数据data"
      },
      {
        "key": "cyrq",
        "name": "出院日期",
        "type": "String",
        "length": "10",
        "required": "是",
        "description": "格式:yyyy-MM-dd",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyts",
        "name": "住院天数",
        "type": "Number",
        "length": "6,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyzddm",
        "name": "主要诊断代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyzdmc",
        "name": "主要诊断名称",
        "type": "String",
        "length": "255",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "cyzddm",
        "name": "次要诊断代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "cyzdmc",
        "name": "次要诊断名称",
        "type": "String",
        "length": "255",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jydybqh",
        "name": "就医地医保区划",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "就医地医保机构的唯一标识，医保结算时必须填写",
        "group": "A-1 发票数据data"
      },
      {
        "key": "xzlx",
        "name": "险种类型",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "详见附录9，医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jzkssj",
        "name": "开始时间",
        "type": "String",
        "length": "19",
        "required": "否",
        "description": "yyyy-MM-dd HH:mm:ss 对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jzjssj",
        "name": "结束时间",
        "type": "String",
        "length": "19",
        "required": "否",
        "description": "yyyy-MM-dd HH:mm:ss 对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "sylb",
        "name": "生育类别",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jhsysslb",
        "name": "计划生育手术类别",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "tc",
        "name": "胎次",
        "type": "Number",
        "length": "3",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yzs",
        "name": "孕周数",
        "type": "Number",
        "length": "2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "tes",
        "name": "胎儿数",
        "type": "Number",
        "length": "3",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "lyfs",
        "name": "离院方式",
        "type": "String",
        "length": "3",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ssczdm",
        "name": "手术操作代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ssczmc",
        "name": "手术操作名称",
        "type": "String",
        "length": "500",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "swrq",
        "name": "死亡日期",
        "type": "String",
        "length": "8",
        "required": "否",
        "description": "yyyyMMdd",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zzysdm",
        "name": "主诊医师代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zzysxm",
        "name": "主诊医师姓名",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyzzddm",
        "name": "住院主诊断代码",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zyzzdmc",
        "name": "住院主诊断名称",
        "type": "String",
        "length": "300",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ylfl",
        "name": "医疗分类",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "详见附录10。对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ddyljgbh",
        "name": "定点医疗机构编号",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ddyljgmc",
        "name": "定点医疗机构名称",
        "type": "String",
        "length": "255",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jgjgdm",
        "name": "监管机构代码",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grzhzf",
        "name": "个人账户支付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "按政策规定用个人账户支付参保人的医疗费用（含基本医疗保险目录范围内和目录范围外的费用）；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "fhfwje",
        "name": "符合范围金额",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "如无金额，填写0。医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ybtcjjzf",
        "name": "医保统筹基金支付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "患者本次就医所发生的医疗费用中按规定由基本医疗保险统筹基金支付的金额；如无金额，填写0。医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "qtybzf",
        "name": "其它医保支付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "患者本次就医所发生的医疗费用中按规定由大病保险、医疗救助、公务员医疗补助、大额补充、企业补充等基金或资金支付的金额；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zfje",
        "name": "自费金额",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "患者本次就医所发生的医疗费用中按照有关规定不属于基本医疗保险目录范围而全部由个人支付的费用；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grzf1",
        "name": "个人自负",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "医保患者起付标准内个人支付费用；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grzf2",
        "name": "个人自付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "患者本次就医所发生的医疗费用中由个人负担的属于基本医疗保险目录范围内自付部分的金额；开展按病种、病组、床日等打包付费方式且由患者定额付费的费用。该项为个人所得税大病医疗专项附加扣除信；息项如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grxjzf",
        "name": "个人现金支付",
        "type": "Number",
        "length": "14,2",
        "required": "是",
        "description": "个人通过现金、银行卡、微信、支付宝等渠道支付的金额；如无金额，填写0",
        "group": "A-1 发票数据data"
      },
      {
        "key": "yjje",
        "name": "预缴金额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "bjje",
        "name": "补缴金额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "tfje",
        "name": "退费金额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "grzhye",
        "name": "个人账户余额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "",
        "group": "A-1 发票数据data"
      },
      {
        "key": "bxzje",
        "name": "报销总金额",
        "type": "Number",
        "length": "14,2",
        "required": "否",
        "description": "医保结算后返回的总金额",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jkr",
        "name": "交款人",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "住院收费明细中的交款人",
        "group": "A-1 发票数据data"
      },
      {
        "key": "skdw",
        "name": "收款单位",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "住院收费明细中的收款单位",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jsh",
        "name": "结算号",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "医保结算后生成的号码/入账唯一值。医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "jssj",
        "name": "结算时间",
        "type": "String",
        "length": "19",
        "required": "否",
        "description": "患者就医时间格式：yyyy-MM-dd HH:mm:ss医保实时结算必填",
        "group": "A-1 发票数据data"
      },
      {
        "key": "ywrq",
        "name": "业务日期",
        "type": "date",
        "length": "",
        "required": "否",
        "description": "业务日期，格式yyyy-MM-dd HH:mm:ss",
        "group": "A-1 发票数据data"
      },
      {
        "key": "fpmx",
        "name": "发票明细",
        "type": "List",
        "length": "",
        "required": "是",
        "description": "发票明细详见A-2,JSON格式列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "sfmx",
        "name": "收费明细",
        "type": "List",
        "length": "",
        "required": "是",
        "description": "收费明细详见A-3,JSON格式列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "sszdyysmx",
        "name": "省市自定义要素明细",
        "type": "List",
        "length": "",
        "required": "否",
        "description": "省市自定义要素明细详见A-4,JSON格式列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "zdxxlb",
        "name": "诊断信息列表",
        "type": "List",
        "length": "",
        "required": "否",
        "description": "诊断信息列表详见A-5,JSON格式列表",
        "group": "A-1 发票数据data"
      },
      {
        "key": "mxxh",
        "name": "明细序号",
        "type": "Number",
        "length": "8",
        "required": "是",
        "description": "明细序号",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "xmmc",
        "name": "项目名称",
        "type": "String",
        "length": "200",
        "required": "是",
        "description": "项目名称，无需传入简称",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "ggxh",
        "name": "规格型号",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "规格型号",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "dw",
        "name": "单位",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "单位",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "sl",
        "name": "数量",
        "type": "String",
        "length": "15,13",
        "required": "否",
        "description": "数量如“单位”栏次非空，则本栏次必须非空。对接医保上传电子结算凭证时，必填",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "dj",
        "name": "单价",
        "type": "String",
        "length": "15,13",
        "required": "否",
        "description": "单价如“单位”栏次非空，则本栏次必须非空。对接医保上传电子结算凭证时，必填",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "je",
        "name": "金额（不含税）",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "金额（不含税）",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "slv",
        "name": "增值税税率/征收率",
        "type": "Number",
        "length": "10,6",
        "required": "是",
        "description": "增值税税率/征收率",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "se",
        "name": "税额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "税额",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "bz",
        "name": "备注",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "备注",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "hsje",
        "name": "含税金额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "含税金额",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "kce",
        "name": "扣除额",
        "type": "Number",
        "length": "16,2",
        "required": "否",
        "description": "扣除额",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "spfwssflbm",
        "name": "商品和服务税收分类编码",
        "type": "String",
        "length": "19",
        "required": "是",
        "description": "商品和服务税收分类编码",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "fphxz",
        "name": "发票行性质",
        "type": "String",
        "length": "2",
        "required": "是",
        "description": "发票行性质00:正常行01:折扣行02:被折扣行",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "yhzcbs",
        "name": "优惠政策标识",
        "type": "String",
        "length": "2",
        "required": "否",
        "description": "优惠政策标识详见附录4",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "fymx",
        "name": "费用明细",
        "type": "String",
        "length": "100",
        "required": "否",
        "description": "",
        "group": "A-2 发票明细fpmx"
      },
      {
        "key": "zysfmxxh",
        "name": "住院收费明细序号",
        "type": "Number",
        "length": "8",
        "required": "是",
        "description": "住院收费明细中对应的明细序号",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "mxxh",
        "name": "发票明细序号",
        "type": "Number",
        "length": "8",
        "required": "是",
        "description": "住院收费明细对应的发票票面明细序号",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "fymx",
        "name": "费用明细",
        "type": "String",
        "length": "33",
        "required": "是",
        "description": "住院收费明细某行明细的项目名称。",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "sl",
        "name": "数量",
        "type": "String",
        "length": "25",
        "required": "否",
        "description": "住院收费明细某行明细的数量",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "dw",
        "name": "单位",
        "type": "String",
        "length": "300",
        "required": "否",
        "description": "住院收费明细某行明细的单位",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "je",
        "name": "金额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "住院收费明细某行明细的金额",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "slv",
        "name": "增值税税率/征收率",
        "type": "Number",
        "length": "10,6",
        "required": "是",
        "description": "增值税税率/征收率",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "se",
        "name": "税额",
        "type": "Number",
        "length": "16,2",
        "required": "是",
        "description": "住院收费明细某行明细的税额",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "ylfwgbm",
        "name": "医疗服务贯标码",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "医疗服务贯标码",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "fyfssj",
        "name": "费用发生时间",
        "type": "String",
        "length": "19",
        "required": "否",
        "description": "yyyy-MM-dd HH:mm:ss。对接医保上传电子结算凭证时，必填",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "ylmlbm",
        "name": "医疗目录编码",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "对接医保上传电子结算凭证时，必填",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "bz",
        "name": "备注",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "备注",
        "group": "A-3 收费明细fpmx"
      },
      {
        "key": "sszdyysxh",
        "name": "省市自定义要素序号",
        "type": "Number",
        "length": "2",
        "required": "是",
        "description": "省市自定义要素序号从“1”开始的连续正整数",
        "group": "A-4 省市自定义要素明细sszdyysmx"
      },
      {
        "key": "sszdyysmc",
        "name": "省市自定义要素名称",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "若“省市自定义要素内容”栏次非空，则本栏次必须非空；",
        "group": "A-4 省市自定义要素明细sszdyysmx"
      },
      {
        "key": "sszdyysnr",
        "name": "省市自定义要素内容",
        "type": "String",
        "length": "33",
        "required": "否",
        "description": "若“省市自定义要素名称”栏次非空，则本栏次必须非空",
        "group": "A-4 省市自定义要素明细sszdyysmx"
      },
      {
        "key": "mxxh",
        "name": "明细序号",
        "type": "Number",
        "length": "8",
        "required": "是",
        "description": "",
        "group": "A-5 诊断列表zdxxlb"
      },
      {
        "key": "cryzdlb",
        "name": "出入院诊断类别",
        "type": "String",
        "length": "6",
        "required": "是",
        "description": "",
        "group": "A-5 诊断列表zdxxlb"
      },
      {
        "key": "zdlb",
        "name": "诊断类别",
        "type": "String",
        "length": "3",
        "required": "是",
        "description": "",
        "group": "A-5 诊断列表zdxxlb"
      },
      {
        "key": "zzzbz",
        "name": "主诊断标志",
        "type": "String",
        "length": "3",
        "required": "是",
        "description": "",
        "group": "A-5 诊断列表zdxxlb"
      },
      {
        "key": "zddm",
        "name": "诊断代码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "A-5 诊断列表zdxxlb"
      },
      {
        "key": "zdmc",
        "name": "诊断名称",
        "type": "String",
        "length": "255",
        "required": "是",
        "description": "",
        "group": "A-5 诊断列表zdxxlb"
      },
      {
        "key": "zdsj",
        "name": "诊断时间",
        "type": "String",
        "length": "19",
        "required": "是",
        "description": "yyyy-MM-dd HH:mm:ss",
        "group": "A-5 诊断列表zdxxlb"
      },
      {
        "key": "zdysdm",
        "name": "诊断医师代码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "A-5 诊断列表zdxxlb"
      },
      {
        "key": "zdysxm",
        "name": "诊断医师姓名",
        "type": "String",
        "length": "50",
        "required": "否",
        "description": "",
        "group": "A-5 诊断列表zdxxlb"
      }
    ],
    "template": {
      "serialNumber": "",
      "kpdbm": "",
      "kpms": "",
      "data": {
        "fppz": "",
        "qyDm": "",
        "cezslxDm": "",
        "xsfnsrsbh": "",
        "xsfmc": "",
        "xsfdz": "",
        "xsfdh": "",
        "xsfkhh": "",
        "xsfzh": "",
        "gmfnsrsbh": "",
        "gmfmc": "",
        "gmfdz": "",
        "gmfdh": "",
        "gmfkhh": "",
        "gmfzh": "",
        "gmfjbr": "",
        "jbrsfzjhm": "",
        "gmfjbrlxdh": "",
        "gmfzrrbz": "",
        "hjje": 0,
        "hjse": 0,
        "jshj": 0,
        "skyhmc": "",
        "skyhzh": "",
        "jsfs": "",
        "ysxwfsd": "",
        "kpr": "",
        "kprzjhm": "",
        "kprzjlx": "",
        "skrxm": "",
        "fhrxm": "",
        "bz": "",
        "zfbzh": "",
        "wxddh": "",
        "sjhm": "",
        "yxdz": "",
        "klx": "",
        "kh": "",
        "yljglx": "",
        "qtyljglx": "",
        "ybjgbm": "",
        "yblxbm": "",
        "qtyblx": "",
        "hzybbh": "",
        "ybxzqhm": "",
        "ryksmc": "",
        "cyksmc": "",
        "hzjzbh": "",
        "zyjzbh": "",
        "hzwyid": "",
        "hzxm": "",
        "hzsfzjlxDm": "",
        "hzsfzjhm": "",
        "xb": "",
        "nl": "",
        "bq": "",
        "ch": "",
        "blh": "",
        "jbbm": "",
        "zyrq": "",
        "cyrq": "",
        "zyts": 0,
        "zyzddm": "",
        "zyzdmc": "",
        "cyzddm": "",
        "cyzdmc": "",
        "jydybqh": "",
        "xzlx": "",
        "jzkssj": "",
        "jzjssj": "",
        "sylb": "",
        "jhsysslb": "",
        "tc": 0,
        "yzs": 0,
        "tes": 0,
        "lyfs": "",
        "ssczdm": "",
        "ssczmc": "",
        "swrq": "",
        "zzysdm": "",
        "zzysxm": "",
        "zyzzddm": "",
        "zyzzdmc": "",
        "ylfl": "",
        "ddyljgbh": "",
        "ddyljgmc": "",
        "jgjgdm": "",
        "grzhzf": 0,
        "fhfwje": 0,
        "ybtcjjzf": 0,
        "qtybzf": 0,
        "zfje": 0,
        "grzf1": 0,
        "grzf2": 0,
        "grxjzf": 0,
        "yjje": 0,
        "bjje": 0,
        "tfje": 0,
        "grzhye": 0,
        "bxzje": 0,
        "jkr": "",
        "skdw": "",
        "jsh": "",
        "jssj": "",
        "ywrq": "",
        "fpmx": [
          {
            "mxxh": 0,
            "xmmc": "",
            "ggxh": "",
            "dw": "",
            "sl": "",
            "dj": "",
            "je": 0,
            "slv": 0,
            "se": 0,
            "bz": "",
            "hsje": 0,
            "kce": 0,
            "spfwssflbm": "",
            "fphxz": "",
            "yhzcbs": "",
            "fymx": ""
          }
        ],
        "sfmx": [
          {
            "zysfmxxh": 0,
            "mxxh": 0,
            "fymx": "",
            "sl": "",
            "dw": "",
            "je": 0,
            "slv": 0,
            "se": 0,
            "ylfwgbm": "",
            "fyfssj": "",
            "ylmlbm": "",
            "bz": ""
          }
        ],
        "sszdyysmx": [
          {
            "sszdyysxh": 0,
            "sszdyysmc": "",
            "sszdyysnr": ""
          }
        ],
        "zdxxlb": [
          {
            "mxxh": 0,
            "cryzdlb": "",
            "zdlb": "",
            "zzzbz": "",
            "zddm": "",
            "zdmc": "",
            "zdsj": "",
            "zdysdm": "",
            "zdysxm": ""
          }
        ]
      }
    }
  },
  {
    "category": "",
    "name": "全电蓝字发票开具结果查询",
    "path": "/api/standard/v1/rpa/102101005",
    "method": "POST",
    "description": "单位内部系统通过流水号和纳税人识别号发起蓝票开具接口服务请求，获取发票开具结果。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.2.3 全电蓝字发票开具结果查询",
    "fields": [
      {
        "key": "serialNumber",
        "name": "流水号",
        "type": "String",
        "length": "32",
        "required": "是",
        "description": "流水号",
        "group": "请求参数"
      },
      {
        "key": "nsrsbh",
        "name": "纳税人识别号",
        "type": "String",
        "length": "26",
        "required": "是",
        "description": "纳税人识别号",
        "group": "请求参数"
      },
      {
        "key": "kpdbm",
        "name": "开票点编码",
        "type": "String",
        "length": "30",
        "required": "否",
        "description": "",
        "group": "请求参数"
      }
    ],
    "template": {
      "serialNumber": "",
      "nsrsbh": "",
      "kpdbm": ""
    }
  },
  {
    "category": "开票接口",
    "name": "全电蓝字发票全额红冲",
    "path": "/api/standard/v1/rpa/102101025",
    "method": "POST",
    "description": "单位内部系统组装红字确认单数据发起全电红字发票开具请求，进行红字确认单申请并开具红票操作，全额冲红全电蓝字发票。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.2.4 全电蓝字发票全额红冲",
    "fields": [
      {
        "key": "serialNumber",
        "name": "流水号",
        "type": "String",
        "length": "32",
        "required": "是",
        "description": "流水号",
        "group": "请求参数"
      },
      {
        "key": "kpdbm",
        "name": "开票点编码",
        "type": "String",
        "length": "30",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "data",
        "name": "确认单数据",
        "type": "String",
        "length": "",
        "required": "是",
        "description": "红字确认单数据，详见：A-1 确认单数据data",
        "group": "请求参数"
      },
      {
        "key": "fqfnsrsbh",
        "name": "发起方纳税人识别号",
        "type": "String",
        "length": "26",
        "required": "是",
        "description": "发起方纳税人识别号",
        "group": "A-1 确认单数据data"
      },
      {
        "key": "lzfpdm",
        "name": "蓝字发票发票代码",
        "type": "String",
        "length": "12",
        "required": "否",
        "description": "蓝字发票发票代码",
        "group": "A-1 确认单数据data"
      },
      {
        "key": "lzfphm",
        "name": "蓝字发票发票号码",
        "type": "String",
        "length": "20",
        "required": "是",
        "description": "蓝字发票发票号码",
        "group": "A-1 确认单数据data"
      },
      {
        "key": "lzkprq",
        "name": "蓝字发票开票时间",
        "type": "date",
        "length": "",
        "required": "是",
        "description": "蓝字发票开票时间yyyy-MM-dd HH:mm:ss",
        "group": "A-1 确认单数据data"
      },
      {
        "key": "lzfplx",
        "name": "蓝字发票类型",
        "type": "String",
        "length": "2",
        "required": "否",
        "description": "见附录5，默认为：81电子发票（增值税专用发票）",
        "group": "A-1 确认单数据data"
      },
      {
        "key": "lzfpjym",
        "name": "蓝字发票校验码",
        "type": "String",
        "length": "6",
        "required": "否",
        "description": "蓝字发票校验码（当蓝字发票为纸质票时必填）",
        "group": "A-1 确认单数据data"
      },
      {
        "key": "chyyDm",
        "name": "红字发票冲红原因代码",
        "type": "String",
        "length": "2",
        "required": "是",
        "description": "红字发票冲红原因代码详见附录6",
        "group": "A-1 确认单数据data"
      }
    ],
    "template": {
      "serialNumber": "",
      "kpdbm": "",
      "data": {
        "fqfnsrsbh": "",
        "lzfpdm": "",
        "lzfphm": "",
        "lzkprq": "",
        "lzfplx": "",
        "lzfpjym": "",
        "chyyDm": ""
      }
    }
  },
  {
    "category": "开票接口",
    "name": "全电发票版式文件下载",
    "path": "/api/standard/v1/rpa/103101006",
    "method": "POST",
    "description": "查询开具的全电发票版式文件，支持PDF。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.2.5 全电发票版式文件下载",
    "fields": [
      {
        "key": "fplx",
        "name": "发票类型",
        "type": "String",
        "length": "2",
        "required": "否",
        "description": "见附录5",
        "group": "请求参数"
      },
      {
        "key": "fphm",
        "name": "发票号码",
        "type": "String",
        "length": "20",
        "required": "是",
        "description": "",
        "group": "请求参数"
      },
      {
        "key": "kprq",
        "name": "开票日期",
        "type": "String",
        "length": "10",
        "required": "是",
        "description": "格式yyyy-MM-dd",
        "group": "请求参数"
      },
      {
        "key": "wjlx",
        "name": "文件类型",
        "type": "String",
        "length": "",
        "required": "否",
        "description": "PDF,OFD, 默认PDF",
        "group": "请求参数"
      }
    ],
    "template": {
      "fplx": "",
      "fphm": "",
      "kprq": "",
      "wjlx": ""
    }
  },
  {
    "category": "发票查看",
    "name": "查看全电发票H5页面地址",
    "path": "/api/standard/v1/rpa/103101014",
    "method": "POST",
    "description": "查询全电发票H5页面地址信息。",
    "sourceDoc": "乐享协同数字化电子发票接口规范（医疗） v1.0.18.docx",
    "sectionTitle": "3.3.1 查看全电发票H5页面地址",
    "fields": [],
    "template": {}
  }
] as const satisfies readonly LexiangInterfaceInfo[];
